const TableHeadings = [
  'Sr.No',
  'Name',
  'Registration Number',
  'Semester',
  'Program',
  'Actions',
];

const AddStudentFormContent = [
  {
    type: 'text',
    name: 'stdRegNumber',
    placeholder: 'Registration Number',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'firstName',
    placeholder: 'First Name',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'lastName',
    placeholder: 'Last Name',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'fatherName',
    placeholder: "Father's Name",
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'fatherOccupation',
    placeholder: "Father's Occupation",
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'password',
    name: 'password',
    placeholder: 'Password',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'date',
    name: 'dateOfBirth',
    placeholder: 'Date of Birth',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'select',
    name: 'section',
    placeholder: 'Select Section',
    value: '',
    onChange: 'handleChange',
    options: [
      { value: '', label: 'Select Section' },
      { value: '1', label: 'Section 1' },
      { value: '2', label: 'Section 2' },
    ],
  },
  {
    type: 'email',
    name: 'email',
    placeholder: 'Email',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'contactNumber',
    placeholder: 'Contact Number',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'select',
    name: 'gender',
    placeholder: 'Select Gender',
    value: '',
    onChange: 'handleChange',
    options: [
      { value: '', label: 'Select Gender' },
      { value: 'M', label: 'Male' },
      { value: 'F', label: 'Female' },
    ],
  },
  {
    type: 'text',
    name: 'cnic',
    placeholder: 'CNIC',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'number',
    name: 'semester',
    placeholder: 'Semester',
    value: '',
    onChange: 'handleChange',
    min: 1,
    max: 8,
  },
  {
    type: 'text',
    name: 'department',
    placeholder: 'Department ID',
    value: '',
    onChange: 'handleChange',
  },
  {
    type: 'text',
    name: 'program',
    placeholder: 'Program Code',
    value: '',
    onChange: 'handleChange',
  },
  // Address fields
  {
    type: 'text',
    name: 'houseNo',
    placeholder: 'House Number',
    value: '',
    onChange: 'handleAddressChange',
  },
  {
    type: 'text',
    name: 'street',
    placeholder: 'Street',
    value: '',
    onChange: 'handleAddressChange',
  },
  {
    type: 'text',
    name: 'town',
    placeholder: 'Town',
    value: '',
    onChange: 'handleAddressChange',
  },
  {
    type: 'text',
    name: 'city',
    placeholder: 'City',
    value: '',
    onChange: 'handleAddressChange',
  },
];

export { TableHeadings, AddStudentFormContent };
